# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            梓非徐
tagline:          '交互、视觉、产品'
description:      '交互设计新人，交互、视觉、产品都想搀和一点儿，可啥都学不好，莫怪莫怪。'
url:              http://zifeixu.com
baseurl:          /

author:
  name:           '梓非徐'
  url:            http://weibo.com/zifeixu

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
