# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            梓非徐
name:			  梓非徐的产品设计
tagline:          'Product Design'
description:      '不会产品的设计，不是好的交互。'
url:              http://zifeixu.com
baseurl:          /


paginate:         16

