# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            梓非徐的产品设计
tagline:          '设计、交互、产品、用户体验'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://zifeixu.com
baseurl:          /

author:
  name:           '梓非徐'
  url:            http://weibo.com/zifeixu

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
