# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            梓非的播客
name:			  梓非的播客
tagline:          'Podcast'
description:      '不会分享的设计师，不是好的主播。'
url:              http://zifeixu.com/fm
baseurl:          /


paginate:         16

